apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: nginx-dhanesh
    image: nginx
    ports:
    - containerPort: 8080
  - name: watcher-dhanesh
    image: akharany/watcher
    ports:
    - containerPort: 8080
