apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: nginx-dhanesh
    image: nginx
    ports:
    - containerPort: 80
  - name: watcher-dhanesh
    image: afakharany/watcher:latest
